# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 2TIN-DevOps17

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://2tindevops.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cdabd29188eb48e19dc639e03bc4d631 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_936ab106a4224590a4bd7352c2d7116b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 2tindevops.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cdabd29188eb48e19dc639e03bc4d631 }}/test:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '2TIN-DevOps17'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b9cf02338aec416a9aff942bff69836d }}
        images: '2tindevops.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cdabd29188eb48e19dc639e03bc4d631 }}/test:${{ github.sha }}'