name: Build and deploy container app to Azure Web App - 2TIN-DevOps17

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://2tindevops.azurecr.io/
          username: 2TINDEVOPS
          password: 5TbkM7bvKOp9GNF0T/s8kF1+a2W8CW/8zcptdh0Cov+ACRDavNC7

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 2tindevops.azurecr.io/2tindevops/test:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          client_id: 'Lars Ballet'
          client_secret: 'Karatekid1234'
          tenant_id: '0bff66c5-45db-46ed-8b81-87959e069b90'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '2TIN-DevOps17'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_2e4fef8a3fe94ca58b7c9737627a2c52 }}
          images: '2tindevops.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_16dd7775cead49268ae05ae8ccfc4b25 }}/test:${{ github.sha }}'
